services:
  auth-ms:
    container_name: ms
    build: .

    ports:
      - '8080:8080'
    env_file:
      - .env
    environment:
      DB_HOST: auth-ms-db
      REDIS_HOST: auth-ms-redis

    depends_on:
      - auth-ms-redis
      - auth-ms-db

  auth-ms-db:
    container_name: auth-db
    image: postgres:17-alpine

    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    volumes:
      - auth-ms-db:/var/lib/postgres/data
    ports:
      - '5432:5432'

  auth-ms-redis:
    container_name: auth-redis
    image: redis

    ports:
      - '6379:6379'

    volumes:
      - auth-ms-redis:/data

volumes:
  auth-ms-db:
  auth-ms-redis: