services:
  db:
    container_name: ms
    image: postgres:17-alpine

    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    volumes:
      - auth-ms:/var/lib/postgres/data
    ports:
      - '5432:5432'

  redis:
    container_name: redis
    image: redis

    ports:
      - '6379:6379'

    volumes:
      - auth-ms:/var/lib/redis/data

volumes:
  auth-ms:

networks:
  auth-ms: