spring:
  datasource:
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1}
    url: jdbc:postgresql://localhost:5432/${DB_NAME:postgres}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    enabled: true

  api-docs:
    enabled: true
